fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /rejestracja

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin-panel

rankingowiec:
    resource: "@RankingowiecBundle/Resources/config/routing.yml"
    prefix:   /
